.TH checkmm 1 "Writer's ScriptBench"
.SH Name
checkmm \- validate a groff -mm file
.SH Description
The
.I checkmm
utility uses Groff's built-in diagnostics
to find issues in
.CW -mm
files, including syntax errors,
unmatched macros,
and structural issues.
.
.SH "Differences from WWB"
First and foremost, this utility requires
.B Groff ,
specifically the diagnostics built into
the Groff
.CW -mm
macros.
.LP
The way this version of
.I checkmm
displays issues greatly differs from
the legacy version.
