.TH hyphen 1 "Writer's ScriptBench"
.SH Name
hyphen \- show hyphenated (broken) words
.SH Synopsis
.I nroff
.RI [ options ]
.IR files ...
|
.I hyphen
.SH Description
.I hyphen
displays a list of words
hyphenated in
.I nroff output.
You can analyze this output
to make sure words are being
hyphenated correctly.
