.TH neg 1 "Writer's ScriptBench"
.SH Name
neg \- show negative words and phrases
.SH Synopsis
.I neg
.IR files ...
.SH Description
.I neg
displays a list of negative
words and phrases.
You can analyze this output
to minimize unnecessary negative constructs.
.SH Notes
You can usually skip using
.I deroff
for this utility.
