.TH acro 1 "Writer's ScriptBench"
.SH Name
acro \- print and count acronyms
.SH Synopsis
.I acro
.RI [ files... ]
.SH Description
.I acro
displays a list of acronyms
found in the list of files
(or standard input).
At the end,
.I acro
shows a count of occurrences
of each acronym found.
.SH "Differences from WWB"
The output is very much different.
.SH Bugs
The acronyms should print in context
so you can see whether it's being used correctly.
